export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_BY_VALUE = 'INCREMENT_BY_VALUE';

export const INIT_ARTICLES = 'INIT_ARTICLES';
export const INIT_ARTICLES_SUCCESS = 'INIT_ARTICLES_SUCCESS';
export const INIT_ARTICLES_FAILURE = 'INIT_ARTICLES_FAILURE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const ADD_ARTICLE = 'ADD_ARTICLE';

export const CHANGE_FILTER_VALUE = 'CHANGE_FILETR_VALUE';
